let DATA = {records:[], reporting:{}, district_total:{}};
const $ = id => document.getElementById(id);
const n = v => Number(v) || 0;
const esc = v => String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const nameOf = r => String(r.name || r.employee || '').trim();
const unitOf = r => String(r.unit_designation || r.station || r.policeStation || r.psName || r.designation || r.post || r.section || '').replace(/\s+/g,' ').trim();
const opening = r => n(r.opening ?? r.opening_balance);
const disposed = r => n(r.disposed ?? r.disposed_total);
const pending = r => n(r.pending ?? r.total_pendency);
const pendingDays = r => n(r.pendingDays ?? r.average_pending_days);
const created = r => n(r.created);
const received = r => n(r.received);
const closed = r => n(r.disposedClosed ?? r.disposed_closed);
const forwarded = r => n(r.disposedForwarded ?? r.disposed_forwarded);
const parked = r => n(r.parked);
const merged = r => n(r.merged);
function workload(r){return opening(r)+created(r)+received(r)}
function score(r){const w=workload(r);const d=w?Math.min(100,disposed(r)/w*100):(pending(r)>0?0:100);const p=w?Math.min(100,pending(r)/w*100):(pending(r)>0?100:0);const age=pending(r)>0?Math.max(0,100-Math.min(100,pendingDays(r)/60*100)):100;return Math.max(0,Math.min(100,d*.5+(100-p)*.3+age*.2))}
function fmt(v){return n(v).toLocaleString('en-IN')}
function setupTabs(){document.querySelectorAll('.tab[data-target]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active-section'));b.classList.add('active');$(b.dataset.target)?.classList.add('active-section')}))}
function rankRow(r,i,bottom=false){return `<div class="rank-item"><b>${bottom?'#'+(i+1):'🏅 '+(i+1)}</b><div><strong>${esc(unitOf(r))}</strong><small>${esc(nameOf(r))}</small></div>${bottom?`<span class="badge red">Pend. ${fmt(pending(r))}</span>`:''}<span class="rank-score">${score(r).toFixed(1)}</span></div>`}
function renderRanks(rows){const sorted=[...rows].sort((a,b)=>score(b)-score(a));$('topList').innerHTML=sorted.slice(0,5).map((r,i)=>rankRow(r,i)).join('');$('bottomList').innerHTML=[...sorted].reverse().slice(0,5).map((r,i)=>rankRow(r,i,true)).join('')}
function renderOldChart(rows){const root=$('barChart');if(!root)return;const top=[...rows].sort((a,b)=>score(b)-score(a)).slice(0,10);root.innerHTML=top.map(r=>`<div class="bar" style="height:${Math.max(8,score(r)*2)}px"><span>${score(r).toFixed(1)}</span><label>${esc(nameOf(r))}</label></div>`).join('')}
function renderPerformance(rows){$('performanceGrid').innerHTML=[...rows].sort((a,b)=>score(b)-score(a)).map(r=>{const w=workload(r);const rate=w?Math.min(100,disposed(r)/w*100):0;return `<div class="perf"><div class="perf-head"><b>${esc(nameOf(r))}</b><strong>${score(r).toFixed(1)}</strong></div><div class="progress"><i style="width:${rate}%"></i></div><small>Disposal rate: ${rate.toFixed(1)}% • Pending: ${fmt(pending(r))} • Avg days: ${pendingDays(r).toFixed(2)}</small></div>`}).join('')}
function summaryRows(items){const max=Math.max(...items.map(x=>x.v),1);return items.map(x=>`<div class="summary-row"><span>${x.k}</span><div class="track"><i style="width:${Math.max(2,x.v/max*100)}%"></i></div><b>${fmt(x.v)}</b></div>`).join('')}
function renderTrends(t){$('movementBars').innerHTML=summaryRows([{k:'Opening Balance',v:n(t.opening_balance)},{k:'Created',v:n(t.created)},{k:'Received',v:n(t.received)},{k:'Disposed',v:n(t.disposed_total)},{k:'Parked',v:n(t.parked)},{k:'Merged',v:n(t.merged)}]);$('pendencyBars').innerHTML=summaryRows([{k:'0–7 Days',v:n(t.pendency_0_7_days)},{k:'8–15 Days',v:n(t.pendency_8_15_days)},{k:'16–30 Days',v:n(t.pendency_16_30_days)},{k:'31–60 Days',v:n(t.pendency_31_60_days)},{k:'>60 Days',v:n(t.pendency_over_60_days)}])}
function renderDetails(rows,filter=''){const q=filter.toLowerCase();const list=rows.filter(r=>(nameOf(r)+' '+unitOf(r)).toLowerCase().includes(q)).sort((a,b)=>score(b)-score(a));$('detailTable').innerHTML=list.map((r,i)=>`<tr><td>${i+1}</td><td><b>${esc(nameOf(r))}</b></td><td>${esc(unitOf(r))}</td><td>${opening(r)}</td><td>${created(r)}</td><td>${received(r)}</td><td>${closed(r)}</td><td>${forwarded(r)}</td><td>${disposed(r)}</td><td>${parked(r)}</td><td>${merged(r)}</td><td>${pending(r)}</td><td>${pendingDays(r).toFixed(2)}</td><td><b>${score(r).toFixed(1)}</b></td></tr>`).join('') || `<tr><td colspan="14">No matching record found.</td></tr>`}
function renderReports(t){const items=[['Opening Balance',t.opening_balance],['Created',t.created],['Received',t.received],['Disposed — Closed',t.disposed_closed],['Disposed — Forwarded',t.disposed_forwarded],['Total Disposed',t.disposed_total],['Parked',t.parked],['Merged',t.merged],['Total Pendency',t.total_pendency],['0–7 Days',t.pendency_0_7_days],['8–15 Days',t.pendency_8_15_days],['16–30 Days',t.pendency_16_30_days],['31–60 Days',t.pendency_31_60_days],['>60 Days',t.pendency_over_60_days],['Average Pending Days',Number(t.average_pending_days||0).toFixed(2)]];$('reportCards').innerHTML=items.map(x=>`<article><span>${x[0]}</span><strong>${typeof x[1]==='number'?fmt(x[1]):x[1]}</strong></article>`).join('')}
function render(){const rows=Array.isArray(DATA.records)?DATA.records:[];const t=DATA.district_total||{};$('period').textContent='Reporting Period: '+(DATA.reporting_period||'—');$('unitCount').textContent=fmt(rows.length);$('disposedHero').textContent=fmt(t.disposed_total);$('pendencyHero').textContent=fmt(t.total_pendency);$('disposedTotal').textContent=fmt(t.disposed_total);$('receivedTotal').textContent=fmt(n(t.created)+n(t.received));$('pendencyTotal').textContent=fmt(t.total_pendency);$('avgPending').textContent=Number(t.average_pending_days||0).toFixed(2);$('tableCount').textContent=rows.length+' records';$('chartNote').textContent=rows.length+' records';renderRanks(rows);renderOldChart(rows);renderPerformance(rows);renderTrends(t);renderDetails(rows);renderReports(t);$('lastLoaded').textContent='Last loaded: '+new Date().toLocaleString('en-IN');document.dispatchEvent(new CustomEvent('eoffice:data-ready'))}
async function load(){try{const res=await fetch('data.json?ts='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error('data.json HTTP '+res.status);DATA=await res.json();render()}catch(e){console.error(e);document.querySelector('main').innerHTML=`<div class="error-box">Data could not be loaded. Please keep data.json in the repository root.</div>`}}
document.addEventListener('DOMContentLoaded',()=>{setupTabs();$('searchRank')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderDetails(DATA.records.filter(r=>(nameOf(r)+' '+unitOf(r)).toLowerCase().includes(q)))});$('searchDetail')?.addEventListener('input',e=>renderDetails(DATA.records,e.target.value));$('refresh')?.addEventListener('click',load);load()});
